CREATE TABLE auteurs (a_id INT PRIMARY KEY, nom VARCHAR(200));
INSERT INTO auteurs VALUES (0,"Federico Santagati");
INSERT INTO auteurs VALUES (1,"Olivier-Marc Nadel");
INSERT INTO auteurs VALUES (2,"Michel Laporte");
INSERT INTO auteurs VALUES (3,"Doris Lessing");
INSERT INTO auteurs VALUES (4,"Michel Deutsch");
INSERT INTO auteurs VALUES (5,"Albert Camus");
INSERT INTO auteurs VALUES (6,"Italo Svevo");
INSERT INTO auteurs VALUES (7,"Guy de Maupassant");
INSERT INTO auteurs VALUES (8,"Brian W. Kernighan");
INSERT INTO auteurs VALUES (9,"José Saramago");
INSERT INTO auteurs VALUES (10,"George Orwell");
INSERT INTO auteurs VALUES (11,"William Faulkner");
INSERT INTO auteurs VALUES (12,"Corneille");
INSERT INTO auteurs VALUES (13,"Ursula LE GUIN");
INSERT INTO auteurs VALUES (14,"Vincent Godeau");
INSERT INTO auteurs VALUES (15,"Fiodor Dostoïevski");
INSERT INTO auteurs VALUES (16,"Salman Rushdie");
INSERT INTO auteurs VALUES (17,"Brian Wilson Aldiss");
INSERT INTO auteurs VALUES (18,"Pierre Boulle");
INSERT INTO auteurs VALUES (19,"Charles Dickens");
INSERT INTO auteurs VALUES (20,"Ovide");
INSERT INTO auteurs VALUES (21,"Toni Morrison");
INSERT INTO auteurs VALUES (22,"Lyon Sprague de Camp");
INSERT INTO auteurs VALUES (23,"Jean-Yves Ferri");
INSERT INTO auteurs VALUES (24,"Miguel de Cervantes");
INSERT INTO auteurs VALUES (25,"Federico Garcia Lorca");
INSERT INTO auteurs VALUES (26,"Dostoïevski Fiodor");
INSERT INTO auteurs VALUES (27,"Astrid Lindgren");
INSERT INTO auteurs VALUES (28,"Publius Maro Vergilius");
INSERT INTO auteurs VALUES (29,"Rob Pike");
INSERT INTO auteurs VALUES (30,"Clifford D. Simak");
INSERT INTO auteurs VALUES (31,"Jorge Luis Borges");
INSERT INTO auteurs VALUES (32,"Dominique Rincé");
INSERT INTO auteurs VALUES (33,"Donald E. Knuth");
INSERT INTO auteurs VALUES (34,"Olivier Py");
INSERT INTO auteurs VALUES (35,"George Eliot");
INSERT INTO auteurs VALUES (36,"Richard Matheson");
INSERT INTO auteurs VALUES (37,"Myriam Martelle");
INSERT INTO auteurs VALUES (38,"Luc Ferry");
INSERT INTO auteurs VALUES (39,"Albert Uderzo");
INSERT INTO auteurs VALUES (40,"Emily Brontë");
INSERT INTO auteurs VALUES (41,"Roger Zelazny");
INSERT INTO auteurs VALUES (42,"Stendhal");
INSERT INTO auteurs VALUES (43,"Didier Poli");
INSERT INTO auteurs VALUES (44,"Kurt Vonnegut");
INSERT INTO auteurs VALUES (45,"Norman Spinrad");
INSERT INTO auteurs VALUES (46,"Robert Sedgewick");
INSERT INTO auteurs VALUES (47,"Thomas Mann");
INSERT INTO auteurs VALUES (48,"Marguerite Yourcenar");
INSERT INTO auteurs VALUES (49,"Ray Bradbury");
INSERT INTO auteurs VALUES (50,"Jonathan Swift");
INSERT INTO auteurs VALUES (51,"Franz Kafka");
INSERT INTO auteurs VALUES (52,"Henrik Ibsen");
INSERT INTO auteurs VALUES (53,"Gérard Chenet");
INSERT INTO auteurs VALUES (54,"Howard Phillips Lovecraft");
INSERT INTO auteurs VALUES (55,"Agathe Demois");
INSERT INTO auteurs VALUES (56,"Jacob Grimm");
INSERT INTO auteurs VALUES (57,"Bruno Karsenti");
INSERT INTO auteurs VALUES (58,"Fédor Mikhaïlovitch Dostoïevski");
INSERT INTO auteurs VALUES (59,"Dim D.");
INSERT INTO auteurs VALUES (60,"Sophocle");
INSERT INTO auteurs VALUES (61,"Gustave Flaubert");
INSERT INTO auteurs VALUES (62,"Frank Herbert");
INSERT INTO auteurs VALUES (63,"Didier Conrad");
INSERT INTO auteurs VALUES (64,"Jean Frémon");
INSERT INTO auteurs VALUES (65,"Virginia Woolf");
INSERT INTO auteurs VALUES (66,"Philip José Farmer");
INSERT INTO auteurs VALUES (67,"Alfred Döblin");
INSERT INTO auteurs VALUES (68,"Hélène Montardre");
INSERT INTO auteurs VALUES (69,"Katsuhiro Ōtomo");
INSERT INTO auteurs VALUES (70,"Michel JEURY");
INSERT INTO auteurs VALUES (71,"Wilhelm Grimm");
INSERT INTO auteurs VALUES (72,"Juan Rulfo");
INSERT INTO auteurs VALUES (73,"Chinua Achebe");
INSERT INTO auteurs VALUES (74,"Honoré de Balzac");
INSERT INTO auteurs VALUES (75,"René Barjavel");
INSERT INTO auteurs VALUES (76,"Aldous HUXLEY");
INSERT INTO auteurs VALUES (77,"Ligaran");
INSERT INTO auteurs VALUES (78,"Gabriel Garcia Márquez");
INSERT INTO auteurs VALUES (79,"René Goscinny");
INSERT INTO auteurs VALUES (80,"William Shakespeare");
INSERT INTO auteurs VALUES (81,"Vladimir Nabokov");
INSERT INTO auteurs VALUES (82,"Virgile");
INSERT INTO auteurs VALUES (83,"Philip K. Dick");
INSERT INTO auteurs VALUES (84,"Robert SILVERBERG");
INSERT INTO auteurs VALUES (85,"Henry S. Warren");
INSERT INTO auteurs VALUES (86,"Naǧīb Maḥfūẓ");
INSERT INTO auteurs VALUES (87,"Günter Grass");
INSERT INTO auteurs VALUES (88,"Isaac Asimov");
INSERT INTO auteurs VALUES (89,"Léon Tolstoï");
INSERT INTO auteurs VALUES (90,"Robert Musil");
INSERT INTO auteurs VALUES (91,"Herman Melville");
INSERT INTO auteurs VALUES (92,"Mark Twain");
INSERT INTO auteurs VALUES (93,"Stefan Wul");
INSERT INTO auteurs VALUES (94,"Johan Faerber");
INSERT INTO auteurs VALUES (95,"Rene Gascony");
INSERT INTO auteurs VALUES (96,"iMinds");
INSERT INTO auteurs VALUES (97,"François Rabelais");
INSERT INTO auteurs VALUES (98,"Gabriel García Márquez");
INSERT INTO auteurs VALUES (99,"Malick Fall");
INSERT INTO auteurs VALUES (100,"Kevin Wayne");
INSERT INTO auteurs VALUES (101,"Pierre Pelot");
INSERT INTO auteurs VALUES (102,"Sébastien Touache");
INSERT INTO auteurs VALUES (103,"Jane Austen");
INSERT INTO auteurs VALUES (104,"Joseph Conrad");
INSERT INTO auteurs VALUES (105,"Elsa Morante");
INSERT INTO auteurs VALUES (106,"Geoffrey Chaucer");
INSERT INTO auteurs VALUES (107,"Ernest Hemingway");
INSERT INTO auteurs VALUES (108,"France Fransa");
INSERT INTO auteurs VALUES (109,"Nikolaï Gogol");
INSERT INTO auteurs VALUES (110,"Marcel Proust");
INSERT INTO auteurs VALUES (111,"J. G. Ballard");
INSERT INTO auteurs VALUES (112,"Clotilde Bruneau");
